# Dockerfile

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies for psycopg2
RUN apt-get update
RUN apt-get install -y libpq-dev build-essential python3-dev

# Install any needed packages specified in requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pip
# RUN pip install psycopg2-binary
RUN pip install Flask
RUN pip install psycopg2
RUN pip install chromadb
RUN pip install weaviate-client
RUN pip install transformers
RUN pip install torch
RUN pip install pymupdf

# RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Expose the port that Flask will run on
EXPOSE 5001

# Define environment variable
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]
